[build]
  publish = "WebApplication3"
  command = ""

[[redirects]]
  from = "/*"
  to = "/WebApplication3/index.html"
  status = 200
  force = true
  conditions = {Not = [
    {Path = ["*.jpg", "*.jpeg", "*.png", "*.gif", "*.webp", "*.mp4", "*.css", "*.js"]}
  ]}

[[redirects]]
  from = "/WebApplication3/wwwroot/*"
  to = "/WebApplication3/wwwroot/:splat"
  status = 200
  force = true 